version: "3.7"

services:
  database:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: muco
      MYSQL_PASSWORD: 123456789
    networks:
      - muconet

  myapp:
    image: olivercw/bookstoreapi:latest
    container_name: myapp
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - muconet

networks:
  muconet: